name: Deploy master branch

on:
  push:
    branches:
      - main

jobs:
  vercel: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - name: Set Env Vars on Vercel Project
        with:
          node-version: 16
          cache: yarn
      - run: yarn install --immutable
      - run: yarn vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - run: yarn vercel deploy --prod --prebuilt --token=${{ secrets.VERCEL_TOKEN }}